# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: RubyGrade
    site_url: http://rubygrade.heroku.com
    
    company_name: 
    admin_email: aglasspool@gmail.com
    
    support_name: Support
    support_email: aglasspool@gmail.com

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
